### ISSUE TITLE
Report Job with space within does not work

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1141]
like "Top Bandwidth Report".
In log 400 bad request

**Comment by ea-at-diladele-com** [comment]
Should be fixed now.
Please make sure the UI checks that a job name only contains spaces/letters/numbers/-, because we need to create a directory with this name and if it contains i.e. backslash or something like that this will fail. it is better even do not allow such names in the first place.
thank you!

**Comment by ra-at-diladele-com** [comment]
done
