### ISSUE TITLE
Need a Docker image for 4.4 when released

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1237]

**Comment by ra-at-diladele-com** [comment]
released as of April, 11 - build number 4.4.0.C405. 
Please update the docker image.

**Comment by ra-at-diladele-com** [comment]
Need to test to https://github.com/diladele/docker-websafety

**Comment by ra-at-diladele-com** [comment]
done; please build and push the image to docker hub. The scripts are at https://github.com/diladele/docker-websafety

**Comment by ea-at-diladele-com** [comment]
It does not work, it seems squid cannot be started, it is recreated all the time.
I see this in the log cache log of squid:
2016/04/24 20:26:55| Set Current Directory to /var/spool/squid
2016/04/24 20:26:55| Starting Squid Cache version 3.5.16 for x86_64-pc-linux-gnu...
2016/04/24 20:26:55| Service Name: squid
2016/04/24 20:26:55| Process ID 109
2016/04/24 20:26:55| Process Roles: master worker
2016/04/24 20:26:55| With 65535 file descriptors available
2016/04/24 20:26:55| Initializing IP Cache...
2016/04/24 20:26:55| DNS Socket created at [::], FD 9
2016/04/24 20:26:55| DNS Socket created at 0.0.0.0, FD 10
2016/04/24 20:26:55| Adding domain localdomain from /etc/resolv.conf
2016/04/24 20:26:55| Adding nameserver 8.8.8.8 from /etc/resolv.conf
2016/04/24 20:26:55| Adding nameserver 8.8.4.4 from /etc/resolv.conf
2016/04/24 20:26:55| helperOpenServers: Starting 5/32 'ssl_crtd' processes
2016/04/24 20:26:55| storeDirWriteCleanLogs: Starting...
2016/04/24 20:26:55|   Finished.  Wrote 0 entries.
2016/04/24 20:26:55|   Took 0.00 seconds (  0.00 entries/sec).
FATAL: Ipc::Mem::Segment::open failed to shm_open(/squid-ssl_session_cache.shm): (2) No such file or directory

**Comment by ra-at-diladele-com** [comment]
I have seen this only once, after restart by supervisord everything seems to be working correctly..

**Comment by ea-at-diladele-com** [comment]
For me, the squid just enters the loop of restarting. each time I see CRIT in the running docker and restarting of squid.

**Comment by ra-at-diladele-com** [comment]
I confirm the bug - have NO idea how to fix it... postponing to 4.6 and later version of Squid...

**Comment by ianbashford** [comment]
Hi,
I wanted to upgrade, so I thought I'd spend some time this evening taking a look.
At first glance, the issue seems to be initialising the swap directories in the docker image with the latest squid.

I commented out the line in start_squid that does this, namely
#    $SQUID_PATH -z -YC -f $SQUID_CONF

Now this is done, the service restarts immediately ( bar the 15 second pause in the script ) -- squid now seems to start first time every time, both on GUI reload and on restart of the docker image.
Sorry I can't explain _why_, but hopefully the _how_ will get this over the hill.

( FWIW I did find this, although I've not tried the patch
http://lists.squid-cache.org/pipermail/squid-users/2015-March/002862.html )

Happy to supply a patch / pull request, although it's not actually a 'fix'.  I don't know the relevance of the line in VMs/bare metal, so maybe it can be skipped just in docker.

I'll try running the docker image I've created for a while, and see if this seems like a good permanent fix

**Comment by ianbashford** [comment]
( sorry about the font there -- must by from the terminal copy and paste )

**Comment by ra-at-diladele-com** [comment]
Hello Ian, I have updated the https://github.com/diladele/docker-websafety with 4.5 version yesterday. Had to go back to Squid 3.3.8 because of unknown error upon startup of squid. This die not seem related to what you describe. May be you could take a look and try building the Dockerfile?

**Comment by ra-at-diladele-com** [comment]
Seems we have problems with upload of SSL certificate for SSL Bump... need to research.

**Comment by ra-at-diladele-com** [comment]
Ian, I have merged your pull request! going to do the extensive test run now.

**Comment by ra-at-diladele-com** [comment]
Ok seems to work nicely; closing the bug then
