### ISSUE TITLE
Beta 4.5.0.1FD2 Squid tool error on pfSense 2.3_1

### ISSUE THREAD

**Issue by QQHeresATissue** [ra-at-diladele-com/qlproxy_external#1317]
When accessing the sidebar option "Tools" under the top bar option "Squid Proxy" a Django debug page is shown.  Selective paste here:

> NoReverseMatch at /squid/tools/upload
> Reverse for 'ToolsUploadWpad' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
> Request Method:	GET
> Request URL:	https://host:8080/squid/tools/upload
> Django Version:	1.6.11
> Exception Type:	NoReverseMatch
> Exception Value:	
> Reverse for 'ToolsUploadWpad' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
> Exception Location:	/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 456
> Python Executable:	/usr/local/bin/python
> Python Version:	2.7.11
> Python Path:	
> ['/opt/qlproxy/var/console',
>  '/usr/local/lib/python2.7/site-packages/django_reportview-0.1-py2.7.egg',
>  '/usr/local/lib/python27.zip',
>  '/usr/local/lib/python2.7',
>  '/usr/local/lib/python2.7/plat-freebsd10',
>  '/usr/local/lib/python2.7/lib-tk',
>  '/usr/local/lib/python2.7/lib-old',
>  '/usr/local/lib/python2.7/lib-dynload',
>  '/usr/local/lib/python2.7/site-packages']

**Comment by ra-at-diladele-com** [comment]
Again I do not have this error. Could you please reinstall the qlproxy package? First remove as in http://docs.diladele.com/administrator_guide_4_5/install/freebsd10/remove.html; then reboot pfsense; add qlproxy user and group again and then install. 

I suspect this is due to incorrect de-installation of the previous version that indeed had this issue.
