### ISSUE TITLE
Shall we deploy a custom build of  DNS server that would also perform filtering on our categories database?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#381]
Something like OpenDNS but in the Vitual Appliance with qlproxy?

**Comment by daleq** [comment]
I'm coming pretty late to the party here...

YES!  I think this would be fabulous.  

It seems this would greatly mitigate the disadvantage of;
"Filtering exceptions need to be managed on the firewall device using rule manipulation commands. It is hard to keep up with the regular changes of the IP addresses of domain names."
in the Non-Explicit (Intercept) Proxying section of the HTTPS Filtering page.
http://docs.diladele.com/administrator_guide_4_2/https_filtering/how.html#way-2-non-explicit-intercept-proxying

I understand this will not do content filtering, but at least one can (easily) block
https://www.BadSite.com since it belongs to the DNS category of "Pron".

This seems like this would be a valuable "middle" option for those who find blocking at a domain/site level for https traffic "good enough" without dealing with certificates, proxies, etc.

I see this as a locally hosted competitor to OpenDNS except it would actually _work_ since many browsers (Firefox/Chrome) don't even seem to use DNS any more.

e.g.  Chrome - Settings : Advanced...
 - Use a web service to help resolve navigation errors
 - Use a prediction service to help complete searches and URLs typed in the address bar or the app launcher search box
 - Predict network actions to improve page load performance
(these are selected by default)

chrome://net-internals/#dns can show all the cached DNS (in the browser!) entries. 

So it appears that OpenDNS FamilyShield is not very useful anymore.  Something that _works_ and has a similar level of functionality seems like a great solution that no one else has at this time (not that I've found).

**Comment by ra-at-diladele-com** [comment]
https://dnssafety.io/
