### ISSUE TITLE
New Report - videos watched on youtube

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#850]
Need to have in 4.3

**Comment by ea-at-diladele-com** [comment]
THis can simply be list of videos, but it is unclear how useful this is. google api cannot be used it seems:
II. Prohibitions
Your API Client will not, and You will not encourage or create functionality for Your users or other third parties to:
1.collect or modify any YouTube user account information;
2.interfere or attempt to interfere in any manner with the proper workings of the YouTube API, or create or distribute any API Client that adversely affects the functionality or performance of YouTube or services provided by YouTube;
3.circumvent or render ineffective any geographical restrictions, including IP address-based restrictions;
4.sell, lease, lend, convey, redistribute, or sublicense to any third party all or any portion of the YouTube API or API Data (except that You may distribute and display the YouTube audiovisual content and accompanying metadata to Your users through Your API Client in a manner that complies with this Agreement);
5.modify or replace the text, images, or other content of the YouTube search results, including (i) changing the order in which search results are presented as YouTube search results, or (ii) intermixing sources other than YouTube when search results are presented as YouTube search results;
**6.modify, replace or otherwise disable the functioning of links to YouTube or third-party websites provided in the YouTube search results or otherwise provided through the YouTube API or YouTube player;
**
**7.modify, replace, interfere with or block advertisements placed by YouTube in the YouTube Data, YouTube audiovisual content, or the YouTube player;

**

**Comment by ra-at-diladele-com** [comment]
The idea is not to block the videos - as this seems to be indeed not allowed by the license agreement, but to let the admin/parent see what video was watched. 

We should parse the requests to youtube/googlevideo the same way we now do for the user search queries report.

**Comment by ra-at-diladele-com** [comment]
Is now at https://github.com/diladele/websafety-issues/issues/4
