### ISSUE TITLE
wsmgr_monitor.json - connection string to sqlite driver should be hardcoded

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#910]
please use the /opt/qlproxy/var/db/monitor2.sqlite
please remove this setting from JSON file and use folders.go to get the path to VAR folder

**Comment by ea-at-diladele-com** [comment]
what about the MySQL string? 
in case when the driver is not SQLite but MySQL it is still necessary to provide a connection string to the server, correct?

**Comment by ea-at-diladele-com** [comment]
In order to create db structure, please make sure you firstly run monitor_db_creator.exe which is compiled in scripts folder.

Now, if the driver is "sqlite3" - the db file is expected at the path var/db/monitor2.sqlite
So please make sure it can is created there by the monitor_db_creator.exe

If everything works as expected please close the bug. Thank you!

**Comment by ra-at-diladele-com** [comment]
The idea for the monitoring the following:
- developers run the monitor db creator for sqlite3 
- the monitor2.sqlite database file is generated and checked in into source tre
- this file is installed on the target machine by installer
- the monitor_db_creator also is installed and is used by the administrator to populate the MySQL database (after changing MySQL settings) or regenerate the monitor2.sqlite when needed.

Neither the installer nor the admin need to run the monitor_db_creator.exe when using sqlite. It should work out of the box.

**Comment by ra-at-diladele-com** [comment]
Added other bugs based on this.
